### ISSUE TITLE
 "Clear Conversation" 功能不起作用

### ISSUE THREAD

**Issue by araea** [danbao/claude-api#1]
## 描述问题

在使用 `claude-api` 时，我尝试使用 "Clear Conversation" 功能，但发现它没有起到清除会话的作用。

## 复现步骤

1. 向 `/claude/chat` 发送一个 POST 请求，设置一个问题作为输入。
2. 收到回复。
3. 向 `/claude/reset` 发送一个 POST 请求，以清除会话。
4. 再次向 `/claude/chat` 发送一个 POST 请求，设置一个不同的问题作为输入。
5. 收到的回复仍然与之前的会话有关，而不是完全基于新的输入。

## 预期行为

在步骤 5 中，我期望收到的回复是基于新输入的，与之前的会话无关。

## 环境和版本信息

- `claude-api` 版本：当前版本
- 操作系统：Windows 10

## 其他信息

如果您需要我提供更多关于此问题的信息，请告诉我。期待您的回复，谢谢！

**Comment by danbao** [comment]
@araea
实验了一下无法复现你的问题，你可以手工在slack输入你的文本试试，因为这个api返回的值本质上就是slack对话框里面的内容 
![image](https://github.com/danbao/claude-api/assets/4090783/2e6f1dab-2a8c-4c76-98c6-09ffa1a94504)

**Comment by araea** [comment]
> @araea 实验了一下无法复现你的问题，你可以手工在slack输入你的文本试试，因为这个api返回的值本质上就是slack对话框里面的内容 ![image](https://user-images.githubusercontent.com/4090783/252150149-2e6f1dab-2a8c-4c76-98c6-09ffa1a94504.png)

# 问题描述优化

## 清楚明确的问题标题
**`/reset` 命令在Claude API中的表现与预期不符**

## 详细的问题描述

我在使用 `claude-api` 项目时发现，当我尝试使用 `/reset` 命令时，其表现与预期不符。我将详细描述我遇到的问题。

### 1. 当前的表现

如下图所示，当我向 `/claude/reset` 发送一个 POST 请求时，Claude 会响应并回复。

![image](https://github.com/danbao/claude-api/assets/120614554/496f1bc1-17c1-4186-91bd-e79975ed4c10)

### 2. 预期的表现

然而，根据我的理解，当使用 Slack-Claude 时，发送 `/reset` 命令应该会有不同的表现，如下图所示：

![image](https://github.com/danbao/claude-api/assets/120614554/eb58067a-c9c1-4776-a214-32585ef436c8)
![image](https://github.com/danbao/claude-api/assets/120614554/cfec8b81-6947-467d-9ac5-3bcca33ea446)

在这种情况下，当 `/reset` 命令发送后，Claude 应该**不会**有回复响应，而只是会提示 `Conversation history forgotten.`。

**Comment by danbao** [comment]
OK,我想想有没办法处理，多谢反馈

**Comment by danbao** [comment]
@araea 更新了prompt，再试试把

**Comment by danbao** [comment]
![image](https://github.com/danbao/claude-api/assets/4090783/459c241d-566e-44d5-af4c-c146f04584da)

**Comment by araea** [comment]
> ![image](https://github.com/danbao/claude-api/assets/4090783/459c241d-566e-44d5-af4c-c146f04584da)
> 


谢谢你❤️
辛苦啦🎉
